flags: {}
extra-package-dbs: []
ghc-options:
  ! '*': -Wall -fno-warn-orphans
packages:
- '.'
- ../Ide3-base
- ../../../HsInterface
extra-deps:
- gi-gdk-3.0.6
- gi-gdkpixbuf-2.0.6
- gi-glib-2.0.6
- haskell-gi-base-0.18.4
- gi-gobject-2.0.6
- gi-gtk-3.0.6
- gi-gtk-hs-0.3.1.0
- gi-pango-1.0.6
compiler: ghc-8.0.1
resolver: nightly-2016-09-01
