flags: {}
extra-package-dbs: []
ghc-options:
  ! '*': -Wall -fno-warn-orphans
packages:
- '.'
- ../Ide3-base
- ../Ide3-common
- ../Ide3-stack
- ../../../HsInterface
extra-deps:
- gi-gtk-hs-0.3.4.0
explicit-setup-deps:
  ! '*': true
resolver: nightly-2017-01-07
